title: Joonatan Huhtasalo's Homepage
page-top-title: Joonatan Huhtasalo
top-section-bg-text: Theoretical physicist working in numerical quantum chemistry
home-subtitle: Joonatan Huhtasalo, BSc in theoretical physics
copyright-text: ''
